// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Abu Ja'far
// Set            : arn
// Collector #    : 1

#[test]
fn pattern_01_triggered_ability() {
    let text = "When this creature dies, destroy all creatures blocking or blocked by it.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "They can't be regenerated.";
    mtg_grammar::parse(text).expect("parse pattern");
}
