// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Aladdin's Lamp
// Set            : arn
// Collector #    : 56

#[test]
fn pattern_01_sentence() {
    let text = "{X}, {T}: The next time you would draw a card this turn, instead look at the top X cards of your library, put all but one of them on the bottom of your library in a random order, then draw a card.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "X can't be 0.";
    mtg_grammar::parse(text).expect("parse pattern");
}
