// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Aladdin
// Set            : arn
// Collector #    : 34

#[test]
fn pattern_01_sentence() {
    let text =
        "{1}{R}{R}, {T}: Gain control of target artifact for as long as you control this creature.";
    mtg_grammar::parse(text).expect("parse pattern");
}
