// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Ali Baba
// Set            : arn
// Collector #    : 35

#[test]
fn pattern_01_sentence() {
    let text = "{R}: Tap target Wall.";
    mtg_grammar::parse(text).expect("parse pattern");
}
