// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Ali from Cairo
// Set            : arn
// Collector #    : 36

#[test]
fn pattern_01_sentence() {
    let text = "Damage that would reduce your life total to less than 1 reduces it to 1 instead.";
    mtg_grammar::parse(text).expect("parse pattern");
}
