// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Animate Wall
// Set            : lea
// Collector #    : 1

#[test]
fn pattern_01_phrase() {
    let text = "Enchant Wall";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_static_ability() {
    let text = "Enchanted Wall can attack as though it didn't have defender.";
    mtg_grammar::parse(text).expect("parse pattern");
}
