// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Ankh of Mishra
// Set            : lea
// Collector #    : 230

#[test]
fn pattern_01_triggered_ability() {
    let text = "Whenever a land enters, this artifact deals 2 damage to that land's controller.";
    mtg_grammar::parse(text).expect("parse pattern");
}

