// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Armageddon
// Set            : lea
// Collector #    : 2

#[test]
fn pattern_01_sentence() {
    let text = "Destroy all lands.";
    mtg_grammar::parse(text).expect("parse pattern");
}
