// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Army of Allah
// Set            : arn
// Collector #    : 2

#[test]
fn pattern_01_sentence() {
    let text = "Attacking creatures get +2/+0 until end of turn.";
    mtg_grammar::parse(text).expect("parse pattern");
}
