// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Bad Moon
// Set            : lea
// Collector #    : 93

#[test]
fn pattern_01_sentence() {
    let text = "Black creatures get +1/+1.";
    mtg_grammar::parse(text).expect("parse pattern");
}
