// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Balance
// Set            : lea
// Collector #    : 3

#[test]
fn pattern_01_sentence() {
    let text = "Each player chooses a number of lands they control equal to the number of lands controlled by the player who controls the fewest, then sacrifices the rest.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "Players discard cards and sacrifice creatures the same way.";
    mtg_grammar::parse(text).expect("parse pattern");
}
