// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Basalt Monolith
// Set            : lea
// Collector #    : 231

#[test]
fn pattern_01_sentence() {
    let text = "This artifact doesn't untap during your untap step.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "{T}: Add {C}{C}{C}.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_03_sentence() {
    let text = "{3}: Untap this artifact.";
    mtg_grammar::parse(text).expect("parse pattern");
}
