// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Bazaar of Baghdad
// Set            : arn
// Collector #    : 70

#[test]
fn pattern_01_sentence() {
    let text = "{T}: Draw two cards, then discard three cards.";
    mtg_grammar::parse(text).expect("parse pattern");
}
