// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Benalish Hero
// Set            : lea
// Collector #    : 4

#[test]
fn pattern_01_phrase() {
    let text = "Banding";
    mtg_grammar::parse(text).expect("parse pattern");
}
