// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Berserk
// Set            : lea
// Collector #    : 185

#[test]
fn pattern_01_sentence() {
    let text = "Cast this spell only before the combat damage step.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text =
        "Target creature gains trample and gets +X/+0 until end of turn, where X is its power.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_03_triggered_ability() {
    let text =
        "At the beginning of the next end step, destroy that creature if it attacked this turn.";
    mtg_grammar::parse(text).expect("parse pattern");
}
