// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Birds of Paradise
// Set            : lea
// Collector #    : 186

#[test]
fn pattern_01_phrase() {
    let text = "Flying";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "{T}: Add one mana of any color.";
    mtg_grammar::parse(text).expect("parse pattern");
}
