// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Black Vise
// Set            : lea
// Collector #    : 233

#[test]
fn pattern_01_sentence() {
    let text = "As this artifact enters, choose an opponent.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_triggered_ability() {
    let text = "At the beginning of the chosen player's upkeep, this artifact deals X damage to that player, where X is the number of cards in their hand minus 4.";
    mtg_grammar::parse(text).expect("parse pattern");
}
