// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Black Ward
// Set            : lea
// Collector #    : 5

#[test]
fn pattern_01_phrase() {
    let text = "Enchant creature";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_static_ability() {
    let text = "Enchanted creature has protection from black.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_03_sentence() {
    let text = "This effect doesn't remove this Aura.";
    mtg_grammar::parse(text).expect("parse pattern");
}
