// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Black Knight
// Set            : lea
// Collector #    : 94

#[test]
fn pattern_01_phrase() {
    let text = "First strike";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_phrase() {
    let text = "Protection from white";
    mtg_grammar::parse(text).expect("parse pattern");
}
