// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Black Lotus
// Set            : lea
// Collector #    : 232

#[test]
fn pattern_01_sentence() {
    let text = "{T}, Sacrifice this artifact: Add three mana of any one color.";
    mtg_grammar::parse(text).expect("parse pattern");
}
