// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Blaze of Glory
// Set            : lea
// Collector #    : 6

#[test]
fn pattern_01_sentence() {
    let text = "Cast this spell only during combat before blockers are declared.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text =
        "Target creature defending player controls can block any number of creatures this turn.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_03_sentence() {
    let text = "It blocks each attacking creature this turn if able.";
    mtg_grammar::parse(text).expect("parse pattern");
}
