// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Blessing
// Set            : lea
// Collector #    : 7

#[test]
fn pattern_01_phrase() {
    let text = "Enchant creature";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "{W}: Enchanted creature gets +1/+1 until end of turn.";
    mtg_grammar::parse(text).expect("parse pattern");
}
