// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Blue Elemental Blast
// Set            : lea
// Collector #    : 49

#[test]
fn pattern_01_phrase() {
    let text = "Choose one —";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "• Counter target red spell.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_03_sentence() {
    let text = "• Destroy target red permanent.";
    mtg_grammar::parse(text).expect("parse pattern");
}
