// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Bog Wraith
// Set            : lea
// Collector #    : 95

#[test]
fn pattern_01_phrase() {
    let text = "Swampwalk";
    mtg_grammar::parse(text).expect("parse pattern");
}
