// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Bottle of Suleiman
// Set            : arn
// Collector #    : 58

#[test]
fn pattern_01_sentence() {
    let text = "{1}, Sacrifice this artifact: Flip a coin.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text =
        "If you win the flip, create a 5/5 colorless Djinn artifact creature token with flying.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_03_sentence() {
    let text = "If you lose the flip, this artifact deals 5 damage to you.";
    mtg_grammar::parse(text).expect("parse pattern");
}
