// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Braingeyser
// Set            : lea
// Collector #    : 50

#[test]
fn pattern_01_sentence() {
    let text = "Target player draws X cards.";
    mtg_grammar::parse(text).expect("parse pattern");
}
