// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Camel
// Set            : arn
// Collector #    : 3

#[test]
fn pattern_01_phrase() {
    let text = "Banding";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_static_ability() {
    let text = "As long as this creature is attacking, prevent all damage Deserts would deal to this creature and to creatures banded with this creature.";
    mtg_grammar::parse(text).expect("parse pattern");
}
