// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Camouflage
// Set            : lea
// Collector #    : 187

#[test]
fn pattern_01_sentence() {
    let text = "Cast this spell only during your declare attackers step.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "This turn, instead of declaring blockers, each defending player chooses any number of creatures they control and divides them into a number of piles equal to the number of attacking creatures for whom that player is the defending player.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_03_sentence() {
    let text = "Creatures those players control that can block additional creatures may likewise be put into additional piles.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_04_sentence() {
    let text = "Assign each pile to a different one of those attacking creatures at random.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_05_sentence() {
    let text =
        "Each creature in a pile that can block the creature that pile is assigned to does so.";
    mtg_grammar::parse(text).expect("parse pattern");
}
