// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Castle
// Set            : lea
// Collector #    : 9

#[test]
fn pattern_01_sentence() {
    let text = "Untapped creatures you control get +0/+2.";
    mtg_grammar::parse(text).expect("parse pattern");
}
