// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Channel
// Set            : lea
// Collector #    : 188

#[test]
fn pattern_01_sentence() {
    let text = "Until end of turn, any time you could activate a mana ability, you may pay 1 life.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "If you do, add {C}.";
    mtg_grammar::parse(text).expect("parse pattern");
}
