// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Chaoslace
// Set            : lea
// Collector #    : 139

#[test]
fn pattern_01_sentence() {
    let text = "Target spell or permanent becomes red.";
    mtg_grammar::parse(text).expect("parse pattern");
}
