// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Chaos Orb
// Set            : lea
// Collector #    : 235

#[test]
fn pattern_01_sentence() {
    let text = "{1}, {T}: If this artifact is on the battlefield, flip it onto the battlefield from a height of at least one foot.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "If this artifact turns over completely at least once during the flip, destroy all nontoken permanents it touches.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_03_sentence() {
    let text = "Then destroy this artifact.";
    mtg_grammar::parse(text).expect("parse pattern");
}
