// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Circle of Protection: Blue
// Set            : lea
// Collector #    : 10

#[test]
fn pattern_01_sentence() {
    let text = "{1}: The next time a blue source of your choice would deal damage to you this turn, prevent that damage.";
    mtg_grammar::parse(text).expect("parse pattern");
}
