// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : City in a Bottle
// Set            : arn
// Collector #    : 60

#[test]
fn pattern_01_triggered_ability() {
    let text = "Whenever one or more other nontoken permanents with a name originally printed in the Arabian Nights expansion are on the battlefield, their controllers sacrifice them.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "Players can't cast spells or play lands with a name originally printed in the Arabian Nights expansion.";
    mtg_grammar::parse(text).expect("parse pattern");
}
