// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : City of Brass
// Set            : arn
// Collector #    : 71

#[test]
fn pattern_01_triggered_ability() {
    let text = "Whenever this land becomes tapped, it deals 1 damage to you.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "{T}: Add one mana of any color.";
    mtg_grammar::parse(text).expect("parse pattern");
}
