// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Clockwork Beast
// Set            : lea
// Collector #    : 236

#[test]
fn pattern_01_sentence() {
    let text = "This creature enters with seven +1/+0 counters on it.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_triggered_ability() {
    let text = "At end of combat, if this creature attacked or blocked this combat, remove a +1/+0 counter from it.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_03_sentence() {
    let text = "{X}, {T}: Put up to X +1/+0 counters on this creature.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_04_sentence() {
    let text = "This ability can't cause the total number of +1/+0 counters on this creature to be greater than seven.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_05_sentence() {
    let text = "Activate only during your upkeep.";
    mtg_grammar::parse(text).expect("parse pattern");
}
