// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Clone
// Set            : lea
// Collector #    : 51

#[test]
fn pattern_01_sentence() {
    let text = "You may have this creature enter as a copy of any creature on the battlefield.";
    mtg_grammar::parse(text).expect("parse pattern");
}
