// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Cockatrice
// Set            : lea
// Collector #    : 189

#[test]
fn pattern_01_phrase() {
    let text = "Flying";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_triggered_ability() {
    let text = "Whenever this creature blocks or becomes blocked by a non-Wall creature, destroy that creature at end of combat.";
    mtg_grammar::parse(text).expect("parse pattern");
}
