// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Conservator
// Set            : lea
// Collector #    : 237

#[test]
fn pattern_01_sentence() {
    let text = "{3}, {T}: Prevent the next 2 damage that would be dealt to you this turn.";
    mtg_grammar::parse(text).expect("parse pattern");
}
