// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Consecrate Land
// Set            : lea
// Collector #    : 14

#[test]
fn pattern_01_phrase() {
    let text = "Enchant land";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_static_ability() {
    let text = "Enchanted land has indestructible and can't be enchanted by other Auras.";
    mtg_grammar::parse(text).expect("parse pattern");
}
