// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Contract from Below
// Set            : lea
// Collector #    : 96

#[test]
fn pattern_01_sentence() {
    let text = "Remove this card from your deck before playing if you're not playing for ante.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "Discard your hand, ante the top card of your library, then draw seven cards.";
    mtg_grammar::parse(text).expect("parse pattern");
}
