// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Control Magic
// Set            : lea
// Collector #    : 52

#[test]
fn pattern_01_phrase() {
    let text = "Enchant creature";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "You control enchanted creature.";
    mtg_grammar::parse(text).expect("parse pattern");
}
