// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Conversion
// Set            : lea
// Collector #    : 15

#[test]
fn pattern_01_triggered_ability() {
    let text = "At the beginning of your upkeep, sacrifice this enchantment unless you pay {W}{W}.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "All Mountains are Plains.";
    mtg_grammar::parse(text).expect("parse pattern");
}
