// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Copper Tablet
// Set            : lea
// Collector #    : 238

#[test]
fn pattern_01_triggered_ability() {
    let text =
        "At the beginning of each player's upkeep, this artifact deals 1 damage to that player.";
    mtg_grammar::parse(text).expect("parse pattern");
}
