// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Copy Artifact
// Set            : lea
// Collector #    : 53

#[test]
fn pattern_01_sentence() {
    let text = "You may have this enchantment enter as a copy of any artifact on the battlefield, except it's an enchantment in addition to its other types.";
    mtg_grammar::parse(text).expect("parse pattern");
}
