// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Counterspell
// Set            : lea
// Collector #    : 54

#[test]
fn pattern_01_sentence() {
    let text = "Counter target spell.";
    mtg_grammar::parse(text).expect("parse pattern");
}
