// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Creature Bond
// Set            : lea
// Collector #    : 55

#[test]
fn pattern_01_phrase() {
    let text = "Enchant creature";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_triggered_ability() {
    let text = "When enchanted creature dies, this Aura deals damage equal to that creature's toughness to the creature's controller.";
    mtg_grammar::parse(text).expect("parse pattern");
}
