// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Crystal Rod
// Set            : lea
// Collector #    : 239

#[test]
fn pattern_01_triggered_ability() {
    let text = "Whenever a player casts a blue spell, you may pay {1}.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "If you do, you gain 1 life.";
    mtg_grammar::parse(text).expect("parse pattern");
}
