// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Cuombajj Witches
// Set            : arn
// Collector #    : 23

#[test]
fn pattern_01_sentence() {
    let text = "{T}: This creature deals 1 damage to any target and 1 damage to any target of an opponent's choice.";
    mtg_grammar::parse(text).expect("parse pattern");
}
