// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Cursed Land
// Set            : lea
// Collector #    : 97

#[test]
fn pattern_01_phrase() {
    let text = "Enchant land";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_triggered_ability() {
    let text = "At the beginning of the upkeep of enchanted land's controller, this Aura deals 1 damage to that player.";
    mtg_grammar::parse(text).expect("parse pattern");
}
