// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Cyclone
// Set            : arn
// Collector #    : 45

#[test]
fn pattern_01_triggered_ability() {
    let text = "At the beginning of your upkeep, put a wind counter on this enchantment, then sacrifice this enchantment unless you pay {G} for each wind counter on it.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "If you pay, this enchantment deals damage equal to the number of wind counters on it to each creature and each player.";
    mtg_grammar::parse(text).expect("parse pattern");
}
