// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Cyclopean Tomb
// Set            : lea
// Collector #    : 240

#[test]
fn pattern_01_sentence() {
    let text = "{2}, {T}: Put a mire counter on target non-Swamp land.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "That land is a Swamp for as long as it has a mire counter on it.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_03_sentence() {
    let text = "Activate only during your upkeep.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_04_triggered_ability() {
    let text = "When this artifact is put into a graveyard from the battlefield, at the beginning of each of your upkeeps for the rest of the game, remove all mire counters from a land that a mire counter was put onto with this artifact but that a mire counter has not been removed from with this artifact.";
    mtg_grammar::parse(text).expect("parse pattern");
}
