// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Darkpact
// Set            : lea
// Collector #    : 99

#[test]
fn pattern_01_sentence() {
    let text = "Remove this card from your deck before playing if you're not playing for ante.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "You own target card in the ante.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_03_sentence() {
    let text = "Exchange that card with the top card of your library.";
    mtg_grammar::parse(text).expect("parse pattern");
}
