// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Dark Ritual
// Set            : lea
// Collector #    : 98

#[test]
fn pattern_01_sentence() {
    let text = "Add {B}{B}{B}.";
    mtg_grammar::parse(text).expect("parse pattern");
}
