// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Death Ward
// Set            : lea
// Collector #    : 17

#[test]
fn pattern_01_sentence() {
    let text = "Regenerate target creature.";
    mtg_grammar::parse(text).expect("parse pattern");
}
