// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Deathgrip
// Set            : lea
// Collector #    : 100

#[test]
fn pattern_01_sentence() {
    let text = "{B}{B}: Counter target green spell.";
    mtg_grammar::parse(text).expect("parse pattern");
}
