// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Demonic Attorney
// Set            : lea
// Collector #    : 102

#[test]
fn pattern_01_sentence() {
    let text = "Remove this card from your deck before playing if you're not playing for ante.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "Each player antes the top card of their library.";
    mtg_grammar::parse(text).expect("parse pattern");
}
