// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Demonic Hordes
// Set            : lea
// Collector #    : 103

#[test]
fn pattern_01_sentence() {
    let text = "{T}: Destroy target land.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_triggered_ability() {
    let text = "At the beginning of your upkeep, unless you pay {B}{B}{B}, tap this creature and sacrifice a land of an opponent's choice.";
    mtg_grammar::parse(text).expect("parse pattern");
}
