// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Demonic Tutor
// Set            : lea
// Collector #    : 104

#[test]
fn pattern_01_sentence() {
    let text = "Search your library for a card, put that card into your hand, then shuffle.";
    mtg_grammar::parse(text).expect("parse pattern");
}
