// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Dingus Egg
// Set            : lea
// Collector #    : 241

#[test]
fn pattern_01_triggered_ability() {
    let text = "Whenever a land is put into a graveyard from the battlefield, this artifact deals 2 damage to that land's controller.";
    mtg_grammar::parse(text).expect("parse pattern");
}
