// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Disenchant
// Set            : lea
// Collector #    : 18

#[test]
fn pattern_01_sentence() {
    let text = "Destroy target artifact or enchantment.";
    mtg_grammar::parse(text).expect("parse pattern");
}
