// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Disintegrate
// Set            : lea
// Collector #    : 140

#[test]
fn pattern_01_sentence() {
    let text = "Disintegrate deals X damage to any target.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "If it's a creature, it can't be regenerated this turn, and if it would die this turn, exile it instead.";
    mtg_grammar::parse(text).expect("parse pattern");
}
