// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Disrupting Scepter
// Set            : lea
// Collector #    : 242

#[test]
fn pattern_01_sentence() {
    let text = "{3}, {T}: Target player discards a card.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "Activate only during your turn.";
    mtg_grammar::parse(text).expect("parse pattern");
}
