// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Dragon Whelp
// Set            : lea
// Collector #    : 141

#[test]
fn pattern_01_phrase() {
    let text = "Flying";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "{R}: This creature gets +1/+0 until end of turn.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_03_sentence() {
    let text = "If this ability has been activated four or more times this turn, sacrifice this creature at the beginning of the next end step.";
    mtg_grammar::parse(text).expect("parse pattern");
}
