// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Drain Power
// Set            : lea
// Collector #    : 56

#[test]
fn pattern_01_sentence() {
    let text = "Target player activates a mana ability of each land they control.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "Then that player loses all unspent mana and you add the mana lost this way.";
    mtg_grammar::parse(text).expect("parse pattern");
}
