// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Drudge Skeletons
// Set            : lea
// Collector #    : 106

#[test]
fn pattern_01_sentence() {
    let text = "{B}: Regenerate this creature.";
    mtg_grammar::parse(text).expect("parse pattern");
}
