// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Dwarven Warriors
// Set            : lea
// Collector #    : 143

#[test]
fn pattern_01_sentence() {
    let text = "{T}: Target creature with power 2 or less can't be blocked this turn.";
    mtg_grammar::parse(text).expect("parse pattern");
}
