// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Dwarven Demolition Team
// Set            : lea
// Collector #    : 142

#[test]
fn pattern_01_sentence() {
    let text = "{T}: Destroy target Wall.";
    mtg_grammar::parse(text).expect("parse pattern");
}
