// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Earthbind
// Set            : lea
// Collector #    : 145

#[test]
fn pattern_01_phrase() {
    let text = "Enchant creature";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_triggered_ability() {
    let text = "When this Aura enters, if enchanted creature has flying, this Aura deals 2 damage to that creature and this Aura gains \"Enchanted creature loses flying.\"";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_03_quoted_keyword() {
    let text = "Enchanted creature loses flying";
    mtg_grammar::parse(text).expect("parse pattern");
}
