// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Earthquake
// Set            : lea
// Collector #    : 146

#[test]
fn pattern_01_sentence() {
    let text = "Earthquake deals X damage to each creature without flying and each player.";
    mtg_grammar::parse(text).expect("parse pattern");
}
