// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Evil Presence
// Set            : lea
// Collector #    : 107

#[test]
fn pattern_01_phrase() {
    let text = "Enchant land";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_static_ability() {
    let text = "Enchanted land is a Swamp.";
    mtg_grammar::parse(text).expect("parse pattern");
}
