// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : False Orders
// Set            : lea
// Collector #    : 147

#[test]
fn pattern_01_sentence() {
    let text = "Cast this spell only during the declare blockers step.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "Remove target creature defending player controls from combat.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_03_sentence() {
    let text = "Creatures it was blocking that had become blocked by only that creature this combat become unblocked.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_04_sentence() {
    let text = "You may have it block an attacking creature of your choice.";
    mtg_grammar::parse(text).expect("parse pattern");
}
