// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Farmstead
// Set            : lea
// Collector #    : 19

#[test]
fn pattern_01_phrase() {
    let text = "Enchant land";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_static_ability() {
    let text = "Enchanted land has \"At the beginning of your upkeep, you may pay {W}{W}. If you do, you gain 1 life.\"";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_03_quoted_keyword() {
    let text = "At the beginning of your upkeep, you may pay {W}{W}. If you do, you gain 1 life";
    mtg_grammar::parse(text).expect("parse pattern");
}
