// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Fastbond
// Set            : lea
// Collector #    : 192

#[test]
fn pattern_01_sentence() {
    let text = "You may play any number of lands on each of your turns.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_triggered_ability() {
    let text = "Whenever you play a land, if it wasn't the first land you played this turn, this enchantment deals 1 damage to you.";
    mtg_grammar::parse(text).expect("parse pattern");
}
