// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Fireball
// Set            : lea
// Collector #    : 149

#[test]
fn pattern_01_sentence() {
    let text = "This spell costs {1} more to cast for each target beyond the first.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "Fireball deals X damage divided evenly, rounded down, among any number of targets.";
    mtg_grammar::parse(text).expect("parse pattern");
}
