// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Flashfires
// Set            : lea
// Collector #    : 151

#[test]
fn pattern_01_sentence() {
    let text = "Destroy all Plains.";
    mtg_grammar::parse(text).expect("parse pattern");
}
