// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Fog
// Set            : lea
// Collector #    : 193

#[test]
fn pattern_01_sentence() {
    let text = "Prevent all combat damage that would be dealt this turn.";
    mtg_grammar::parse(text).expect("parse pattern");
}
