// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Force of Nature
// Set            : lea
// Collector #    : 194

#[test]
fn pattern_01_phrase() {
    let text = "Trample";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_triggered_ability() {
    let text = "At the beginning of your upkeep, this creature deals 8 damage to you unless you pay {G}{G}{G}{G}.";
    mtg_grammar::parse(text).expect("parse pattern");
}
