// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Forcefield
// Set            : lea
// Collector #    : 243

#[test]
fn pattern_01_sentence() {
    let text = "{1}: The next time an unblocked creature of your choice would deal combat damage to you this turn, prevent all but 1 of that damage.";
    mtg_grammar::parse(text).expect("parse pattern");
}
