// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Fork
// Set            : lea
// Collector #    : 152

#[test]
fn pattern_01_sentence() {
    let text = "Copy target instant or sorcery spell, except that the copy is red.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "You may choose new targets for the copy.";
    mtg_grammar::parse(text).expect("parse pattern");
}
