// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Fungusaur
// Set            : lea
// Collector #    : 195

#[test]
fn pattern_01_triggered_ability() {
    let text = "Whenever this creature is dealt damage, put a +1/+1 counter on it.";
    mtg_grammar::parse(text).expect("parse pattern");
}
