// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Gaea's Liege
// Set            : lea
// Collector #    : 196

#[test]
fn pattern_01_static_ability() {
    let text = "As long as Gaea's Liege isn't attacking, its power and toughness are each equal to the number of Forests you control.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_static_ability() {
    let text = "As long as Gaea's Liege is attacking, its power and toughness are each equal to the number of Forests defending player controls.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_03_sentence() {
    let text = "{T}: Target land becomes a Forest until this creature leaves the battlefield.";
    mtg_grammar::parse(text).expect("parse pattern");
}
