// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Gauntlet of Might
// Set            : lea
// Collector #    : 244

#[test]
fn pattern_01_sentence() {
    let text = "Red creatures get +1/+1.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_triggered_ability() {
    let text = "Whenever a Mountain is tapped for mana, its controller adds an additional {R}.";
    mtg_grammar::parse(text).expect("parse pattern");
}
