// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Giant Growth
// Set            : lea
// Collector #    : 197

#[test]
fn pattern_01_sentence() {
    let text = "Target creature gets +3/+3 until end of turn.";
    mtg_grammar::parse(text).expect("parse pattern");
}
