// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Giant Spider
// Set            : lea
// Collector #    : 198

#[test]
fn pattern_01_phrase() {
    let text = "Reach";
    mtg_grammar::parse(text).expect("parse pattern");
}
