// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Glasses of Urza
// Set            : lea
// Collector #    : 245

#[test]
fn pattern_01_sentence() {
    let text = "{T}: Look at target player's hand.";
    mtg_grammar::parse(text).expect("parse pattern");
}
