// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Gloom
// Set            : lea
// Collector #    : 110

#[test]
fn pattern_01_sentence() {
    let text = "White spells cost {3} more to cast.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "Activated abilities of white enchantments cost {3} more to activate.";
    mtg_grammar::parse(text).expect("parse pattern");
}
