// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Goblin Balloon Brigade
// Set            : lea
// Collector #    : 153

#[test]
fn pattern_01_sentence() {
    let text = "{R}: This creature gains flying until end of turn.";
    mtg_grammar::parse(text).expect("parse pattern");
}
