// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Goblin King
// Set            : lea
// Collector #    : 154

#[test]
fn pattern_01_sentence() {
    let text = "Other Goblins get +1/+1 and have mountainwalk.";
    mtg_grammar::parse(text).expect("parse pattern");
}
