// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Guardian Angel
// Set            : lea
// Collector #    : 21

#[test]
fn pattern_01_sentence() {
    let text = "Prevent the next X damage that would be dealt to any target this turn.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "Until end of turn, you may pay {1} any time you could cast an instant.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_03_sentence() {
    let text = "If you do, prevent the next 1 damage that would be dealt to that permanent or player this turn.";
    mtg_grammar::parse(text).expect("parse pattern");
}
