// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Healing Salve
// Set            : lea
// Collector #    : 22

#[test]
fn pattern_01_phrase() {
    let text = "Choose one —";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "• Target player gains 3 life.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_03_sentence() {
    let text = "• Prevent the next 3 damage that would be dealt to any target this turn.";
    mtg_grammar::parse(text).expect("parse pattern");
}
