// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Helm of Chatzuk
// Set            : lea
// Collector #    : 246

#[test]
fn pattern_01_sentence() {
    let text = "{1}, {T}: Target creature gains banding until end of turn.";
    mtg_grammar::parse(text).expect("parse pattern");
}
