// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Howl from Beyond
// Set            : lea
// Collector #    : 111

#[test]
fn pattern_01_sentence() {
    let text = "Target creature gets +X/+0 until end of turn.";
    mtg_grammar::parse(text).expect("parse pattern");
}
