// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Howling Mine
// Set            : lea
// Collector #    : 247

#[test]
fn pattern_01_triggered_ability() {
    let text = "At the beginning of each player's draw step, if this artifact is untapped, that player draws an additional card.";
    mtg_grammar::parse(text).expect("parse pattern");
}
