// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Hurricane
// Set            : lea
// Collector #    : 200

#[test]
fn pattern_01_sentence() {
    let text = "Hurricane deals X damage to each creature with flying and each player.";
    mtg_grammar::parse(text).expect("parse pattern");
}
