// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Hypnotic Specter
// Set            : lea
// Collector #    : 112

#[test]
fn pattern_01_phrase() {
    let text = "Flying";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_triggered_ability() {
    let text = "Whenever this creature deals damage to an opponent, that player discards a card at random.";
    mtg_grammar::parse(text).expect("parse pattern");
}
