// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Ice Storm
// Set            : lea
// Collector #    : 201

#[test]
fn pattern_01_sentence() {
    let text = "Destroy target land.";
    mtg_grammar::parse(text).expect("parse pattern");
}
