// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Icy Manipulator
// Set            : lea
// Collector #    : 248

#[test]
fn pattern_01_sentence() {
    let text = "{1}, {T}: Tap target artifact, creature, or land.";
    mtg_grammar::parse(text).expect("parse pattern");
}
