// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Invisibility
// Set            : lea
// Collector #    : 59

#[test]
fn pattern_01_phrase() {
    let text = "Enchant creature";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_static_ability() {
    let text = "Enchanted creature can't be blocked except by Walls.";
    mtg_grammar::parse(text).expect("parse pattern");
}
