// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Ironclaw Orcs
// Set            : lea
// Collector #    : 159

#[test]
fn pattern_01_sentence() {
    let text = "This creature can't block creatures with power 2 or greater.";
    mtg_grammar::parse(text).expect("parse pattern");
}
