// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Island Sanctuary
// Set            : lea
// Collector #    : 25

#[test]
fn pattern_01_sentence() {
    let text = "If you would draw a card during your draw step, instead you may skip that draw.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "If you do, until your next turn, you can't be attacked except by creatures with flying and/or islandwalk.";
    mtg_grammar::parse(text).expect("parse pattern");
}
