// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Jade Monolith
// Set            : lea
// Collector #    : 252

#[test]
fn pattern_01_sentence() {
    let text = "{1}: The next time a source of your choice would deal damage to target creature this turn, that source deals that damage to you instead.";
    mtg_grammar::parse(text).expect("parse pattern");
}
