// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Jade Statue
// Set            : lea
// Collector #    : 253

#[test]
fn pattern_01_sentence() {
    let text = "{2}: This artifact becomes a 3/6 Golem artifact creature until end of combat.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "Activate only during combat.";
    mtg_grammar::parse(text).expect("parse pattern");
}
