// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Jayemdae Tome
// Set            : lea
// Collector #    : 254

#[test]
fn pattern_01_sentence() {
    let text = "{4}, {T}: Draw a card.";
    mtg_grammar::parse(text).expect("parse pattern");
}
