// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Juggernaut
// Set            : lea
// Collector #    : 255

#[test]
fn pattern_01_sentence() {
    let text = "This creature attacks each combat if able.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "This creature can't be blocked by Walls.";
    mtg_grammar::parse(text).expect("parse pattern");
}
