// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Jump
// Set            : lea
// Collector #    : 60

#[test]
fn pattern_01_sentence() {
    let text = "Target creature gains flying until end of turn.";
    mtg_grammar::parse(text).expect("parse pattern");
}
