// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Karma
// Set            : lea
// Collector #    : 26

#[test]
fn pattern_01_triggered_ability() {
    let text = "At the beginning of each player's upkeep, this enchantment deals damage to that player equal to the number of Swamps they control.";
    mtg_grammar::parse(text).expect("parse pattern");
}
