// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Keldon Warlord
// Set            : lea
// Collector #    : 160

#[test]
fn pattern_01_sentence() {
    let text = "Keldon Warlord's power and toughness are each equal to the number of non-Wall creatures you control.";
    mtg_grammar::parse(text).expect("parse pattern");
}
