// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Kormus Bell
// Set            : lea
// Collector #    : 256

#[test]
fn pattern_01_sentence() {
    let text = "All Swamps are 1/1 black creatures that are still lands.";
    mtg_grammar::parse(text).expect("parse pattern");
}
