// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Kudzu
// Set            : lea
// Collector #    : 204

#[test]
fn pattern_01_phrase() {
    let text = "Enchant land";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_triggered_ability() {
    let text = "When enchanted land becomes tapped, destroy it.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_03_sentence() {
    let text = "That land's controller may attach this Aura to a land of their choice.";
    mtg_grammar::parse(text).expect("parse pattern");
}
