// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Ley Druid
// Set            : lea
// Collector #    : 205

#[test]
fn pattern_01_sentence() {
    let text = "{T}: Untap target land.";
    mtg_grammar::parse(text).expect("parse pattern");
}
