// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Library of Leng
// Set            : lea
// Collector #    : 257

#[test]
fn pattern_01_sentence() {
    let text = "You have no maximum hand size.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "If an effect causes you to discard a card, discard it, but you may put it on top of your library instead of into your graveyard.";
    mtg_grammar::parse(text).expect("parse pattern");
}
