// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Lich
// Set            : lea
// Collector #    : 113

#[test]
fn pattern_01_sentence() {
    let text = "As this enchantment enters, you lose life equal to your life total.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "You don't lose the game for having 0 or less life.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_03_sentence() {
    let text = "If you would gain life, draw that many cards instead.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_04_triggered_ability() {
    let text = "Whenever you're dealt damage, sacrifice that many nontoken permanents.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_05_sentence() {
    let text = "If you can't, you lose the game.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_06_triggered_ability() {
    let text =
        "When this enchantment is put into a graveyard from the battlefield, you lose the game.";
    mtg_grammar::parse(text).expect("parse pattern");
}
