// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Lifetap
// Set            : lea
// Collector #    : 61

#[test]
fn pattern_01_triggered_ability() {
    let text = "Whenever a Forest an opponent controls becomes tapped, you gain 1 life.";
    mtg_grammar::parse(text).expect("parse pattern");
}
