// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Lightning Bolt
// Set            : lea
// Collector #    : 161

#[test]
fn pattern_01_sentence() {
    let text = "Lightning Bolt deals 3 damage to any target.";
    mtg_grammar::parse(text).expect("parse pattern");
}
