// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Living Lands
// Set            : lea
// Collector #    : 209

#[test]
fn pattern_01_sentence() {
    let text = "All Forests are 1/1 creatures that are still lands.";
    mtg_grammar::parse(text).expect("parse pattern");
}
