// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Living Artifact
// Set            : lea
// Collector #    : 208

#[test]
fn pattern_01_phrase() {
    let text = "Enchant artifact";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_triggered_ability() {
    let text = "Whenever you're dealt damage, put that many vitality counters on this Aura.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_03_triggered_ability() {
    let text = "At the beginning of your upkeep, you may remove a vitality counter from this Aura.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_04_sentence() {
    let text = "If you do, you gain 1 life.";
    mtg_grammar::parse(text).expect("parse pattern");
}
