// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Lord of the Pit
// Set            : lea
// Collector #    : 114

#[test]
fn pattern_01_phrase() {
    let text = "Flying, trample";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_triggered_ability() {
    let text = "At the beginning of your upkeep, sacrifice a creature other than this creature.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_03_sentence() {
    let text = "If you can't, this creature deals 7 damage to you.";
    mtg_grammar::parse(text).expect("parse pattern");
}
