// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Lord of Atlantis
// Set            : lea
// Collector #    : 62

#[test]
fn pattern_01_sentence() {
    let text = "Other Merfolk get +1/+1 and have islandwalk.";
    mtg_grammar::parse(text).expect("parse pattern");
}
