// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Lure
// Set            : lea
// Collector #    : 211

#[test]
fn pattern_01_phrase() {
    let text = "Enchant creature";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "All creatures able to block enchanted creature do so.";
    mtg_grammar::parse(text).expect("parse pattern");
}
