// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Magical Hack
// Set            : lea
// Collector #    : 63

#[test]
fn pattern_01_sentence() {
    let text = "Change the text of target spell or permanent by replacing all instances of one basic land type with another.";
    mtg_grammar::parse(text).expect("parse pattern");
}
