// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Manabarbs
// Set            : lea
// Collector #    : 163

#[test]
fn pattern_01_triggered_ability() {
    let text =
        "Whenever a player taps a land for mana, this enchantment deals 1 damage to that player.";
    mtg_grammar::parse(text).expect("parse pattern");
}
