// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Mana Short
// Set            : lea
// Collector #    : 65

#[test]
fn pattern_01_sentence() {
    let text = "Tap all lands target player controls and that player loses all unspent mana.";
    mtg_grammar::parse(text).expect("parse pattern");
}
