// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Mana Vault
// Set            : lea
// Collector #    : 259

#[test]
fn pattern_01_sentence() {
    let text = "This artifact doesn't untap during your untap step.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_triggered_ability() {
    let text = "At the beginning of your upkeep, you may pay {4}.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_03_sentence() {
    let text = "If you do, untap this artifact.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_04_triggered_ability() {
    let text =
        "At the beginning of your draw step, if this artifact is tapped, it deals 1 damage to you.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_05_sentence() {
    let text = "{T}: Add {C}{C}{C}.";
    mtg_grammar::parse(text).expect("parse pattern");
}
