// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Mana Flare
// Set            : lea
// Collector #    : 162

#[test]
fn pattern_01_triggered_ability() {
    let text = "Whenever a player taps a land for mana, that player adds one mana of any type that land produced.";
    mtg_grammar::parse(text).expect("parse pattern");
}
