// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Meekstone
// Set            : lea
// Collector #    : 260

#[test]
fn pattern_01_sentence() {
    let text =
        "Creatures with power 3 or greater don't untap during their controllers' untap steps.";
    mtg_grammar::parse(text).expect("parse pattern");
}
