// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Mesa Pegasus
// Set            : lea
// Collector #    : 28

#[test]
fn pattern_01_phrase() {
    let text = "Flying; banding";
    mtg_grammar::parse(text).expect("parse pattern");
}
