// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Mind Twist
// Set            : lea
// Collector #    : 115

#[test]
fn pattern_01_sentence() {
    let text = "Target player discards X cards at random.";
    mtg_grammar::parse(text).expect("parse pattern");
}
