// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Natural Selection
// Set            : lea
// Collector #    : 212

#[test]
fn pattern_01_sentence() {
    let text =
        "Look at the top three cards of target player's library, then put them back in any order.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "You may have that player shuffle.";
    mtg_grammar::parse(text).expect("parse pattern");
}
