// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Nether Shadow
// Set            : lea
// Collector #    : 116

#[test]
fn pattern_01_phrase() {
    let text = "Haste";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_triggered_ability() {
    let text = "At the beginning of your upkeep, if this card is in your graveyard with three or more creature cards above it, you may put this card onto the battlefield.";
    mtg_grammar::parse(text).expect("parse pattern");
}
