// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Nettling Imp
// Set            : lea
// Collector #    : 117

#[test]
fn pattern_01_sentence() {
    let text = "{T}: Choose target non-Wall creature the active player has controlled continuously since the beginning of the turn.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "That creature attacks this turn if able.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_03_sentence() {
    let text = "Destroy it at the beginning of the next end step if it didn't attack this turn.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_04_sentence() {
    let text = "Activate only during an opponent's turn, before attackers are declared.";
    mtg_grammar::parse(text).expect("parse pattern");
}
