// Generated by `cargo xtask grammar-fix`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Nevinyrral's Disk
// Set            : lea
// Collector #    : 266

#[test]
fn pattern_01_sentence() {
    let text = "This artifact enters tapped.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "{1}, {T}: Destroy all artifacts, creatures, and enchantments.";
    mtg_grammar::parse(text).expect("parse pattern");
}
