// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Nightmare
// Set            : lea
// Collector #    : 118

#[test]
fn pattern_01_phrase() {
    let text = "Flying";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text =
        "Nightmare's power and toughness are each equal to the number of Swamps you control.";
    mtg_grammar::parse(text).expect("parse pattern");
}
