// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Northern Paladin
// Set            : lea
// Collector #    : 29

#[test]
fn pattern_01_sentence() {
    let text = "{W}{W}, {T}: Destroy target black permanent.";
    mtg_grammar::parse(text).expect("parse pattern");
}
