// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Orcish Artillery
// Set            : lea
// Collector #    : 165

#[test]
fn pattern_01_sentence() {
    let text = "{T}: This creature deals 2 damage to any target and 3 damage to you.";
    mtg_grammar::parse(text).expect("parse pattern");
}
