// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Orcish Oriflamme
// Set            : lea
// Collector #    : 166

#[test]
fn pattern_01_sentence() {
    let text = "Attacking creatures you control get +1/+0.";
    mtg_grammar::parse(text).expect("parse pattern");
}
