// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Paralyze
// Set            : lea
// Collector #    : 119

#[test]
fn pattern_01_phrase() {
    let text = "Enchant creature";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_triggered_ability() {
    let text = "When this Aura enters, tap enchanted creature.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_03_static_ability() {
    let text = "Enchanted creature doesn't untap during its controller's untap step.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_04_triggered_ability() {
    let text = "At the beginning of the upkeep of enchanted creature's controller, that player may pay {4}.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_05_sentence() {
    let text = "If the player does, untap the creature.";
    mtg_grammar::parse(text).expect("parse pattern");
}
