// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Personal Incarnation
// Set            : lea
// Collector #    : 31

#[test]
fn pattern_01_sentence() {
    let text = "{0}: The next 1 damage that would be dealt to this creature this turn is dealt to its owner instead.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "Only this creatures owner may activate this ability.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_03_triggered_ability() {
    let text = "When this creature dies, its owner loses half their life, rounded up.";
    mtg_grammar::parse(text).expect("parse pattern");
}
