// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Pestilence
// Set            : lea
// Collector #    : 120

#[test]
fn pattern_01_triggered_ability() {
    let text = "At the beginning of the end step, if no creatures are on the battlefield, sacrifice this enchantment.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "{B}: This enchantment deals 1 damage to each creature and each player.";
    mtg_grammar::parse(text).expect("parse pattern");
}
