// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Phantasmal Terrain
// Set            : lea
// Collector #    : 68

#[test]
fn pattern_01_phrase() {
    let text = "Enchant land";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "As this Aura enters, choose a basic land type.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_03_static_ability() {
    let text = "Enchanted land is the chosen type.";
    mtg_grammar::parse(text).expect("parse pattern");
}
