// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Pirate Ship
// Set            : lea
// Collector #    : 70

#[test]
fn pattern_01_sentence() {
    let text = "This creature can't attack unless defending player controls an Island.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "{T}: This creature deals 1 damage to any target.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_03_triggered_ability() {
    let text = "When you control no Islands, sacrifice this creature.";
    mtg_grammar::parse(text).expect("parse pattern");
}
