// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Plague Rats
// Set            : lea
// Collector #    : 121

#[test]
fn pattern_01_sentence() {
    let text = "Plague Rats's power and toughness are each equal to the number of creatures named Plague Rats on the battlefield.";
    mtg_grammar::parse(text).expect("parse pattern");
}
