// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Power Leak
// Set            : lea
// Collector #    : 71

#[test]
fn pattern_01_phrase() {
    let text = "Enchant enchantment";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_triggered_ability() {
    let text = "At the beginning of the upkeep of enchanted enchantment's controller, that player may pay any amount of mana.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_03_sentence() {
    let text = "This Aura deals 2 damage to that player.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_04_sentence() {
    let text = "Prevent X of that damage, where X is the amount of mana that player paid this way.";
    mtg_grammar::parse(text).expect("parse pattern");
}
