// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Power Surge
// Set            : lea
// Collector #    : 167

#[test]
fn pattern_01_triggered_ability() {
    let text = "At the beginning of each player's upkeep, this enchantment deals X damage to that player, where X is the number of untapped lands they controlled at the beginning of this turn.";
    mtg_grammar::parse(text).expect("parse pattern");
}
