// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Power Sink
// Set            : lea
// Collector #    : 72

#[test]
fn pattern_01_sentence() {
    let text = "Counter target spell unless its controller pays {X}.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "If that player doesn't, they tap all lands with mana abilities they control and lose all unspent mana.";
    mtg_grammar::parse(text).expect("parse pattern");
}
