// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Psionic Blast
// Set            : lea
// Collector #    : 74

#[test]
fn pattern_01_sentence() {
    let text = "Psionic Blast deals 4 damage to any target and 2 damage to you.";
    mtg_grammar::parse(text).expect("parse pattern");
}
