// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Raging River
// Set            : lea
// Collector #    : 168

#[test]
fn pattern_01_triggered_ability() {
    let text = "Whenever one or more creatures you control attack, each defending player divides all creatures without flying they control into a \"left\" pile and a \"right\" pile.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_quoted_keyword() {
    let text = "Left";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_03_quoted_keyword() {
    let text = "Right";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_04_sentence() {
    let text = "Then, for each attacking creature you control, choose \"left\" or \"right.\" That creature can't be blocked this combat except by creatures with flying and creatures in a pile with the chosen label.";
    mtg_grammar::parse(text).expect("parse pattern");
}
