// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Regeneration
// Set            : lea
// Collector #    : 213

#[test]
fn pattern_01_phrase() {
    let text = "Enchant creature";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "{G}: Regenerate enchanted creature.";
    mtg_grammar::parse(text).expect("parse pattern");
}
