// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Regrowth
// Set            : lea
// Collector #    : 214

#[test]
fn pattern_01_sentence() {
    let text = "Return target card from your graveyard to your hand.";
    mtg_grammar::parse(text).expect("parse pattern");
}
