// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Resurrection
// Set            : lea
// Collector #    : 34

#[test]
fn pattern_01_sentence() {
    let text = "Return target creature card from your graveyard to the battlefield.";
    mtg_grammar::parse(text).expect("parse pattern");
}
