// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Reverse Damage
// Set            : lea
// Collector #    : 35

#[test]
fn pattern_01_sentence() {
    let text = "The next time a source of your choice would deal damage to you this turn, prevent that damage.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "You gain life equal to the damage prevented this way.";
    mtg_grammar::parse(text).expect("parse pattern");
}
