// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Righteousness
// Set            : lea
// Collector #    : 36

#[test]
fn pattern_01_sentence() {
    let text = "Target blocking creature gets +7/+7 until end of turn.";
    mtg_grammar::parse(text).expect("parse pattern");
}
