// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Rock Hydra
// Set            : lea
// Collector #    : 171

#[test]
fn pattern_01_sentence() {
    let text = "This creature enters with X +1/+1 counters on it.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "For each 1 damage that would be dealt to this creature, if it has a +1/+1 counter on it, remove a +1/+1 counter from it and prevent that 1 damage.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_03_sentence() {
    let text = "{R}: Prevent the next 1 damage that would be dealt to this creature this turn.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_04_sentence() {
    let text = "{R}{R}{R}: Put a +1/+1 counter on this creature.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_05_sentence() {
    let text = "Activate only during your upkeep.";
    mtg_grammar::parse(text).expect("parse pattern");
}
