// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Royal Assassin
// Set            : lea
// Collector #    : 123

#[test]
fn pattern_01_sentence() {
    let text = "{T}: Destroy target tapped creature.";
    mtg_grammar::parse(text).expect("parse pattern");
}
