// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Sacrifice
// Set            : lea
// Collector #    : 124

#[test]
fn pattern_01_sentence() {
    let text = "As an additional cost to cast this spell, sacrifice a creature.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "Add an amount of {B} equal to the sacrificed creature's mana value.";
    mtg_grammar::parse(text).expect("parse pattern");
}
