// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Scavenging Ghoul
// Set            : lea
// Collector #    : 126

#[test]
fn pattern_01_triggered_ability() {
    let text = "At the beginning of each end step, put a corpse counter on this creature for each creature that died this turn.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "Remove a corpse counter from this creature: Regenerate this creature.";
    mtg_grammar::parse(text).expect("parse pattern");
}
