// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Sedge Troll
// Set            : lea
// Collector #    : 172

#[test]
fn pattern_01_sentence() {
    let text = "This creature gets +1/+1 as long as you control a Swamp.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "{B}: Regenerate this creature.";
    mtg_grammar::parse(text).expect("parse pattern");
}
