// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Serra Angel
// Set            : lea
// Collector #    : 39

#[test]
fn pattern_01_phrase() {
    let text = "Flying";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_phrase() {
    let text = "Vigilance";
    mtg_grammar::parse(text).expect("parse pattern");
}
