// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Simulacrum
// Set            : lea
// Collector #    : 128

#[test]
fn pattern_01_sentence() {
    let text = "You gain life equal to the damage dealt to you this turn.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "Simulacrum deals damage to target creature you control equal to the damage dealt to you this turn.";
    mtg_grammar::parse(text).expect("parse pattern");
}
