// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Siren's Call
// Set            : lea
// Collector #    : 77

#[test]
fn pattern_01_sentence() {
    let text = "Cast this spell only during an opponent's turn, before attackers are declared.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "Creatures the active player controls attack this turn if able.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_03_triggered_ability() {
    let text = "At the beginning of the next end step, destroy all non-Wall creatures that player controls that didn't attack this turn.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_04_sentence() {
    let text = "Ignore this effect for each creature the player didn't control continuously since the beginning of the turn.";
    mtg_grammar::parse(text).expect("parse pattern");
}
