// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Sleight of Mind
// Set            : lea
// Collector #    : 78

#[test]
fn pattern_01_sentence() {
    let text = "Change the text of target spell or permanent by replacing all instances of one color word with another.";
    mtg_grammar::parse(text).expect("parse pattern");
}
