// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Smoke
// Set            : lea
// Collector #    : 175

#[test]
fn pattern_01_sentence() {
    let text = "Players can't untap more than one creature during their untap steps.";
    mtg_grammar::parse(text).expect("parse pattern");
}
