// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Soul Net
// Set            : lea
// Collector #    : 270

#[test]
fn pattern_01_triggered_ability() {
    let text = "Whenever a creature dies, you may pay {1}.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "If you do, you gain 1 life.";
    mtg_grammar::parse(text).expect("parse pattern");
}
