// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Spell Blast
// Set            : lea
// Collector #    : 79

#[test]
fn pattern_01_sentence() {
    let text = "Counter target spell with mana value X.";
    mtg_grammar::parse(text).expect("parse pattern");
}
