// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Stasis
// Set            : lea
// Collector #    : 80

#[test]
fn pattern_01_sentence() {
    let text = "Players skip their untap steps.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_triggered_ability() {
    let text = "At the beginning of your upkeep, sacrifice this enchantment unless you pay {U}.";
    mtg_grammar::parse(text).expect("parse pattern");
}
