// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Stone Giant
// Set            : lea
// Collector #    : 176

#[test]
fn pattern_01_sentence() {
    let text = "{T}: Target creature you control with toughness less than this creature's power gains flying until end of turn.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "Destroy that creature at the beginning of the next end step.";
    mtg_grammar::parse(text).expect("parse pattern");
}
