// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Stream of Life
// Set            : lea
// Collector #    : 217

#[test]
fn pattern_01_sentence() {
    let text = "Target player gains X life.";
    mtg_grammar::parse(text).expect("parse pattern");
}
