// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Sunglasses of Urza
// Set            : lea
// Collector #    : 271

#[test]
fn pattern_01_sentence() {
    let text = "You may spend white mana as though it were red mana.";
    mtg_grammar::parse(text).expect("parse pattern");
}
