// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Swords to Plowshares
// Set            : lea
// Collector #    : 40

#[test]
fn pattern_01_sentence() {
    let text = "Exile target creature.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "Its controller gains life equal to its power.";
    mtg_grammar::parse(text).expect("parse pattern");
}
