// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Terror
// Set            : lea
// Collector #    : 130

#[test]
fn pattern_01_sentence() {
    let text = "Destroy target nonartifact, nonblack creature.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "It can't be regenerated.";
    mtg_grammar::parse(text).expect("parse pattern");
}
