// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : The Hive
// Set            : lea
// Collector #    : 272

#[test]
fn pattern_01_sentence() {
    let text =
        "{5}, {T}: Create a 1/1 colorless Insect artifact creature token with flying named Wasp.";
    mtg_grammar::parse(text).expect("parse pattern");
}
