// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Time Vault
// Set            : lea
// Collector #    : 274

#[test]
fn pattern_01_sentence() {
    let text = "This artifact enters tapped.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "This artifact doesn't untap during your untap step.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_03_sentence() {
    let text = "If you would begin your turn while this artifact is tapped, you may skip that turn instead.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_04_sentence() {
    let text = "If you do, untap this artifact.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_05_sentence() {
    let text = "{T}: Take an extra turn after this one.";
    mtg_grammar::parse(text).expect("parse pattern");
}
