// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Timetwister
// Set            : lea
// Collector #    : 84

#[test]
fn pattern_01_sentence() {
    let text =
        "Each player shuffles their hand and graveyard into their library, then draws seven cards.";
    mtg_grammar::parse(text).expect("parse pattern");
}
