// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Time Walk
// Set            : lea
// Collector #    : 83

#[test]
fn pattern_01_sentence() {
    let text = "Take an extra turn after this one.";
    mtg_grammar::parse(text).expect("parse pattern");
}
