// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Twiddle
// Set            : lea
// Collector #    : 85

#[test]
fn pattern_01_sentence() {
    let text = "You may tap or untap target artifact, creature, or land.";
    mtg_grammar::parse(text).expect("parse pattern");
}
