// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Two-Headed Giant of Foriys
// Set            : lea
// Collector #    : 179

#[test]
fn pattern_01_phrase() {
    let text = "Trample";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "This creature can block an additional creature each combat.";
    mtg_grammar::parse(text).expect("parse pattern");
}
