// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Unsummon
// Set            : lea
// Collector #    : 86

#[test]
fn pattern_01_sentence() {
    let text = "Return target creature to its owner's hand.";
    mtg_grammar::parse(text).expect("parse pattern");
}
