// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Verduran Enchantress
// Set            : lea
// Collector #    : 222

#[test]
fn pattern_01_triggered_ability() {
    let text = "Whenever you cast an enchantment spell, you may draw a card.";
    mtg_grammar::parse(text).expect("parse pattern");
}
