// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Vesuvan Doppelganger
// Set            : lea
// Collector #    : 87

#[test]
fn pattern_01_sentence() {
    let text = "You may have this creature enter as a copy of any creature on the battlefield, except it doesn't copy that creature's color and it has \"At the beginning of your upkeep, you may have this creature become a copy of target creature, except it doesn't copy that creature's color and it has this ability.\"";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_quoted_keyword() {
    let text = "At the beginning of your upkeep, you may have this creature become a copy of target creature, except it doesn't copy that creature's color and it has this ability";
    mtg_grammar::parse(text).expect("parse pattern");
}
