// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Veteran Bodyguard
// Set            : lea
// Collector #    : 41

#[test]
fn pattern_01_static_ability() {
    let text = "As long as this creature is untapped, all damage that would be dealt to you by unblocked creatures is dealt to this creature instead.";
    mtg_grammar::parse(text).expect("parse pattern");
}
