// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Volcanic Eruption
// Set            : lea
// Collector #    : 88

#[test]
fn pattern_01_sentence() {
    let text = "Destroy X target Mountains.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "Volcanic Eruption deals damage to each creature and each player equal to the number of Mountains put into a graveyard this way.";
    mtg_grammar::parse(text).expect("parse pattern");
}
