// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Web
// Set            : lea
// Collector #    : 228

#[test]
fn pattern_01_phrase() {
    let text = "Enchant creature";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_static_ability() {
    let text = "Enchanted creature gets +0/+2 and has reach.";
    mtg_grammar::parse(text).expect("parse pattern");
}
