// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Wheel of Fortune
// Set            : lea
// Collector #    : 183

#[test]
fn pattern_01_sentence() {
    let text = "Each player discards their hand, then draws seven cards.";
    mtg_grammar::parse(text).expect("parse pattern");
}
