// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Wild Growth
// Set            : lea
// Collector #    : 229

#[test]
fn pattern_01_phrase() {
    let text = "Enchant land";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_triggered_ability() {
    let text = "Whenever enchanted land is tapped for mana, its controller adds an additional {G}.";
    mtg_grammar::parse(text).expect("parse pattern");
}
