// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Winter Orb
// Set            : lea
// Collector #    : 275

#[test]
fn pattern_01_static_ability() {
    let text = "As long as this artifact is untapped, players can't untap more than one land during their untap steps.";
    mtg_grammar::parse(text).expect("parse pattern");
}
