// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Word of Command
// Set            : lea
// Collector #    : 136

#[test]
fn pattern_01_sentence() {
    let text = "Look at target opponent's hand and choose a card from it.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "You control that player until Word of Command finishes resolving.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_03_sentence() {
    let text = "The player plays that card if able.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_04_sentence() {
    let text = "While doing so, the player can activate mana abilities only if they're from lands that player controls and only if mana they produce is spent to activate other mana abilities of lands the player controls and/or to play that card.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_05_sentence() {
    let text = "If the chosen card is cast as a spell, you control the player while that spell is resolving.";
    mtg_grammar::parse(text).expect("parse pattern");
}
