// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Wrath of God
// Set            : lea
// Collector #    : 45

#[test]
fn pattern_01_sentence() {
    let text = "Destroy all creatures.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "They can't be regenerated.";
    mtg_grammar::parse(text).expect("parse pattern");
}
