// Generated by `cargo xtask add-card`.
// Parse-only pattern tests for incrementally growing grammar support.
//
// Card           : Zombie Master
// Set            : lea
// Collector #    : 137

#[test]
fn pattern_01_sentence() {
    let text = "Other Zombie creatures have swampwalk.";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_02_sentence() {
    let text = "Other Zombies have \"{B}: Regenerate this permanent.\"";
    mtg_grammar::parse(text).expect("parse pattern");
}

#[test]
fn pattern_03_quoted_keyword() {
    let text = "{B}: Regenerate this permanent";
    mtg_grammar::parse(text).expect("parse pattern");
}
