use std::path::{Path, PathBuf};
use std::process::ExitCode;

use anyhow::{Context, Result};

use mtg_corpus::{find_next_failing_card, NextCard};
use mtg_scryfall::{Card, ScryfallClient};

use crate::paths::{generated_tests_dir, generated_tests_manifest};

/// Default starting set when the user doesn't pass `--set`. Walking
/// Magic forward from Alpha matches "easy patterns first".
const DEFAULT_SET: &str = "lea";

pub fn run(args: &[String]) -> ExitCode {
    let set_code = parse_set(args).unwrap_or_else(|| DEFAULT_SET.to_string());
    match run_inner(&set_code) {
        Ok(code) => code,
        Err(e) => {
            eprintln!("error: {e:#}");
            ExitCode::FAILURE
        }
    }
}

fn run_inner(set_code: &str) -> Result<ExitCode> {
    let client = ScryfallClient::new()?;
    match find_next_failing_card(&client, set_code)? {
        NextCard::AllPass => {
            println!("All cards in {set_code} pass the round-trip assertion.");
            Ok(ExitCode::SUCCESS)
        }
        NextCard::Failing {
            card,
            reason,
            normalized,
        } => {
            print_failure(&card, &reason, &normalized);
            let path =
                generate_test_file(&card, &normalized).context("write generated test file")?;
            register_test(&path).context("register generated test in manifest")?;
            println!();
            println!("Wrote {}", path.display());
            println!("Remove `#[ignore]` to start iterating; promote to tests/ when it passes.");
            Ok(ExitCode::SUCCESS)
        }
    }
}

fn print_failure(card: &Card, reason: &str, normalized: &str) {
    println!();
    println!("First failing card in {}:", card.set_code);
    println!("  Name           : {}", card.name);
    println!("  Collector #    : {}", card.collector_number);
    println!("  Oracle text    :");
    for line in card.oracle_text.lines() {
        println!("    {line}");
    }
    if normalized != card.oracle_text {
        println!("  Normalized     :");
        for line in normalized.lines() {
            println!("    {line}");
        }
    }
    println!("  Round-trip says: {reason}");
}

fn generate_test_file(card: &Card, normalized: &str) -> Result<PathBuf> {
    let dir = generated_tests_dir();
    std::fs::create_dir_all(&dir).with_context(|| format!("create {}", dir.display()))?;
    let slug = slugify(&card.name);
    let path = dir.join(format!("{slug}.rs"));
    if path.exists() {
        // Overwriting could destroy in-progress work. Surface this; user
        // can delete the existing file if they want a regeneration.
        anyhow::bail!("generated test already exists: {}", path.display());
    }
    let body = render_test(card, normalized);
    std::fs::write(&path, body).with_context(|| format!("write {}", path.display()))?;
    Ok(path)
}

fn render_test(card: &Card, normalized: &str) -> String {
    format!(
        "// Auto-generated by `cargo xtask next-card`. Remove the `#[ignore]`\n\
         // when you start iterating on this card; promote it out of tests/generated\n\
         // (and update tests/generated.rs) once it passes.\n\
         //\n\
         // Card           : {name}\n\
         // Set            : {set}\n\
         // Collector #    : {collector}\n\n\
         #[test]\n\
         #[ignore = \"generated by xtask next-card; un-ignore to iterate\"]\n\
         fn round_trip() {{\n    \
             let text = {text:?};\n    \
             let ast = mtg_grammar::parse(text).expect(\"parse\");\n    \
             let reprinted = mtg_grammar::unparse(&ast);\n    \
             let ast2 = mtg_grammar::parse(&reprinted).expect(\"reparse\");\n    \
             assert_eq!(ast, ast2);\n\
         }}\n",
        name = card.name,
        set = card.set_code,
        collector = card.collector_number,
        text = normalized,
    )
}

fn register_test(test_path: &Path) -> Result<()> {
    let manifest = generated_tests_manifest();
    let slug = test_path
        .file_stem()
        .expect("test file has a stem")
        .to_string_lossy()
        .to_string();
    let entry = format!("#[path = \"generated/{slug}.rs\"]\nmod {slug};\n");

    let mut text = if manifest.exists() {
        std::fs::read_to_string(&manifest)
            .with_context(|| format!("read {}", manifest.display()))?
    } else {
        manifest_header().to_string()
    };
    if text.contains(&format!("mod {slug};")) {
        return Ok(());
    }
    if !text.ends_with('\n') {
        text.push('\n');
    }
    text.push_str(&entry);
    std::fs::write(&manifest, text).with_context(|| format!("write {}", manifest.display()))?;
    Ok(())
}

fn manifest_header() -> &'static str {
    "// Manifest of generated round-trip tests. Each entry is created by\n\
     // `cargo xtask next-card`. Generated tests live under tests/generated/\n\
     // and are #[ignore]'d until you start working on them.\n\n"
}

fn slugify(name: &str) -> String {
    let mut s = String::with_capacity(name.len());
    let mut prev_underscore = false;
    for c in name.chars() {
        if c.is_ascii_alphanumeric() {
            s.push(c.to_ascii_lowercase());
            prev_underscore = false;
        } else if !prev_underscore && !s.is_empty() {
            s.push('_');
            prev_underscore = true;
        }
    }
    let trimmed = s.trim_end_matches('_');
    if trimmed.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        format!("card_{trimmed}")
    } else {
        trimmed.to_string()
    }
}

fn parse_set(args: &[String]) -> Option<String> {
    let mut iter = args.iter();
    while let Some(a) = iter.next() {
        match a.as_str() {
            "--set" => return iter.next().cloned(),
            s if s.starts_with("--set=") => return Some(s["--set=".len()..].to_string()),
            _ => {}
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::slugify;

    #[test]
    fn slugify_basic() {
        assert_eq!(slugify("Lightning Bolt"), "lightning_bolt");
    }

    #[test]
    fn slugify_punctuation_and_apostrophes() {
        assert_eq!(slugify("Sol'kanar the Tainted"), "sol_kanar_the_tainted");
    }

    #[test]
    fn slugify_dfc_separator() {
        assert_eq!(
            slugify("Akki Lavarunner // Tok-Tok, Volcano Born"),
            "akki_lavarunner_tok_tok_volcano_born",
        );
    }

    #[test]
    fn slugify_prefixes_leading_digit() {
        assert_eq!(slugify("4th-place Roach"), "card_4th_place_roach");
    }
}
